### ISSUE TITLE
Adding media to tell some stories and contextualize all of these links

### ISSUE THREAD

**Issue by Aycrazy** [kylehalleman/covid19inwi#16]
Richie Burke, host of Gogedders, is cool with us embedding the audio of this episode on the assitance page. I'm thinking it can go above "How to help" [here](https://github.com/kylehalleman/covid19inwi/blob/master/assets/add_audio.png)

**Comment by kylehalleman** [comment]
Given the redesign, and "How to Help" being the `h1` on the page—the podcast should probably go below the `h1` and table of contents, but before the first `h2` (General volunteering and donating).

**Comment by kylehalleman** [comment]
Closing as this has been added.
