### ISSUE TITLE
broken link to "contribute"?

### ISSUE THREAD

**Issue by BarkleyBG** [kylehalleman/covid19inwi#19]
https://www.covid19inwi.com/contribute.html does not seem to work (for me)

I also echo #15 : would be great to "create more welcoming/inviting language to have people contribute on Github"

**Comment by BarkleyBG** [comment]
I'd love to add a link to the symptom survey on WeCountCOVID19.com . Amy and I can help you with the link. Should I open up another GH issue for adding this link?

**Comment by kylehalleman** [comment]
@BarkleyBG You can open another issue if you would like to provide specific messaging for the link.

I am not running into any issues with the contribute page. Do you have a 404 or some other type of error? What do you see?

And yes I agree with the comment in #15 about updating the language. I've made an omnibus issue we can use for today's Code for Milwaukee meeting: see #20

**Comment by BarkleyBG** [comment]
When i click contribute, nothing happens. I sit on the (bottom of) the main page. 

I'll try on mobile, too.

**Comment by BarkleyBG** [comment]
NEVERMIND it works just fine. My mistake. closing this issue :)
