### ISSUE TITLE
Update WeCountCOVID19.com link and blurb

### ISSUE THREAD

**Issue by BarkleyBG** [kylehalleman/covid19inwi#28]
Hey yall, could you update the link to WeCountCOVID19.com, directly? We just published our new website, so please send people there.

Perhaps the following? 

> WeCountCOVID19.com is a grassroots survey of anyone who is possibly sick with coronavirus. If you're sick, please visit the website to take the anonymous 5-minute survey to help understand what and where the symptoms of COVID-19 are. The website also provides data analysis reports of the survey results that are available for anyone to view. This is a joint effort from members of Code for Milwaukee and UW-Milwaukee's School of Public Health.

**Comment by BarkleyBG** [comment]
Thank you!

**Comment by kylehalleman** [comment]
Done. Thanks for the update!
